### ISSUE TITLE
[BUG] HandleDir w/ DirOptions Cache.Enable serves malformed content

### ISSUE THREAD

**Issue by AlbinoGeek** [kataras/iris#1580]
## Summary

Serving files with `HandleDir`, `Dir` with the both Compress and Cache enabled causes malformed PNGs to be delivered.

## Reproduction
1. clone the sample code repository
2. `go build -o server main.go ; sudo ./server`
3. Try to load the app using Firefox, Chrome, etc.
4. Disable `Cache` and notice everything works

## Actual Behaviour
The images are malformed and the CSS is sometimes served as a corrupted binary.

The CSS comes into Firefox like so:
```css
���	n����a���body {
background-color: #000;
color: #fff;
}

h1 {
font-family: 'Source Code Pro', monospace;
}
�M1qVa���
```

## Expected Behaviour
The images and CSS should load correctly.

## Versions, etc
|Thing|Version|
|-|-|
|Golang|1.14.6 linux/amd64|
|Iris|master|
|Kernel|5.7.14-200.fc32.x86_64|
|OS|Fedora 32 Workstation|

## Sample Code
https://github.com/AlbinoGeek/iris-cache-issue

**Comment by kataras** [comment]
@AlbinoGeek You don't have to set the `Compression: true`, the `iris.DirOptions.Cache` serves **compressed data** for the client already, no any on-fly compression is used when the client accepts a compression that the server does implements too (such as gzip, brotli, snappy, deflate). But I am curious how is that even fired, the `Compress` field should be checked only when the file is NOT cached: https://github.com/kataras/iris/blob/ff5e43f341cce0cf79be9e68edcb58a1c13efda4/core/router/fs.go#L291-L301

**Comment by kataras** [comment]
Wow I've just seen your example you use `app.Use(iris.Compression)` that's why this is happening...the **cached content is already gzipped** and you try to compress that again with that middleware.

**Comment by kataras** [comment]
Fixed @AlbinoGeek, thanks for opening that one 👍

**Comment by AlbinoGeek** [comment]
Thank you @kataras !  The intention was to cache the HTML being served, hence the general `app.Use(iris.Compression)`

**Comment by AlbinoGeek** [comment]
Unfortunately, I must ask this be re-opened. Even after removing `app.Use(iris.Compression)` the failure still happens. Even after pulling `master` again to make sure I've updated my code, and it includes the commit you have pushed. It would appear that the automatic caching for `HandleDir` stuff is broken at the moment.

I have updated the code sample repository to match.

**Comment by kataras** [comment]
@AlbinoGeek it renders here with the correct data, could you please try to clear the browser cache?

**Comment by AlbinoGeek** [comment]
I apologize, you are correct. This was an issue of me having to wipe out `$GOPATH/pkg/mod` for the update to take.

**Comment by kataras** [comment]
No worries, great I could help!
