### ISSUE TITLE
Websocket demo not working on Safari/Mac combination

### ISSUE THREAD

**Issue by nkev** [kataras/iris#175]
There is an error with the websocket demo: If you open 2 browsers and send a message in each one, and then close one of the browsers the Go program crashes.with:

```bash
      |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ v3.0.0-beta.4
                                                                                 
Tue, 07 Jun 2016 20:41:52 GMT: Running at :8080
 
websocket: close 1006 (abnormal closure): unexpected EOF
 
Connection with ID: ZezSUboKTqWKQweuhKtpGqcjRvcNUJnNXeSEsctLMiLuDMdEILcPaXINySfseofU ha
s been disconnected!panic: runtime error: invalid memory address or nil pointer derefer
ence
[signal 0xb code=0x1 addr=0x50 pc=0x13fdb5]
 
goroutine 16 [running]:
panic(0x692a00, 0xc82000a0e0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0xc8203aa480, 0xecee89c61, 0
xc8330d353e, 0xaffda0, 0x0, 0x0)
        <autogenerated>:35 +0x75
github.com/iris-contrib/websocket.(*Conn).write(0xc8201ab320, 0x8, 0xecee89c61, 0x330d3
53e, 0xaffda0, 0xc820041cc0, 0x2, 0x2, 0x0, 0x0)
        /Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:293 +0x12c
github.com/iris-contrib/websocket.(*Conn).flushFrame(0xc8201ab320, 0x1, 0x0, 0x0, 0x0,
0x0, 0x0)
        /Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:455 +0x713
github.com/iris-contrib/websocket.(*Conn).WriteMessage(0xc8201ab320, 0x8, 0xb1d6a0, 0x0
, 0x0, 0x0, 0x0)
        /Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:595 +0x18c
github.com/kataras/iris/websocket.(*connection).write(0xc82007f200, 0x8, 0xb1d6a0, 0x0,
 0x0, 0x0, 0x0)
        /Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/connection.go:84 +
0x1aa
github.com/kataras/iris/websocket.(*connection).writer(0xc82007f200)
        /Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/connection.go:98 +
0x1b7
created by github.com/kataras/iris/websocket.(*server).handleConnection
        /Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/server.go:86 +0x88
exit status 2
```

**Comment by kataras** [comment]
@nkev  I tried to re-procude the error and I couldn't, I opened two tabs , one chrome one firefox, send a message from firefox -> chrome and chrome -> firefox and close firefox, after a while close chrome, and the opposite again and no error shows up, **can you please post a .gif** ?

**Comment by kataras** [comment]
@nkev  I tried to re-preduce the error and I couldn't, I opened two tabs , one chrome one firefox, send a message from firefox -> chrome and chrome -> firefox and close firefox, after a while close chrome, and the opposite again and no error shows up, **can you please post a .gif** ?

**Comment by nkev** [comment]
I just tried it in Windows and it works ok. The problem seems to happen on Mac (not sure about Linux). If you open Chrome on Mac and then Safari on same Mac, send a message from each and then close Safari browser, it happens every time.

**Comment by kataras** [comment]
To tell the truth, I didn't try it with Safari, whenever you could login to your iMac try with other browser and tell me the results please, I don't have any macos (virtual or not) running on my machine, so I will need your help to fix any issue :/

**Comment by nkev** [comment]
No problem. It's late here in Sydney and I need to sleep, but I will look into it tomorrow.

**Comment by kataras** [comment]
Ok thanks you, if you can change/edit the issue title to something more specific, people will scary from this title xD. Good night!

**Comment by nkev** [comment]
Ok, I just downloaded Firefox on Mac and it works ok with Chrome on Mac. So the app only crashes when you close the Safari browser window on Mac. I am using Macbook Pro running El Capitan 10.11.5 and Safari v9.1.1 (11601.6.17). ΚΑΛΗΝΥΧΤΑ! (I am from Izmir, Turkey :))

**Comment by nkev** [comment]
Can anyone else using a Mac please confirm the bug?

**Comment by sebtzm** [comment]
I have the same bug on Windows with Chrome.
This is the code that gives me the error:

```
func SetupWebSocket() {

	iris.Config().Websocket.Endpoint = "/ws"
	
	ws := iris.Websocket() 

	ws.OnConnection(func(c websocket.Connection) {

		fmt.Printf("On connection '%s' \n", c.ID())

		c.OnMessage(func(message []byte) {
			
			fmt.Println("Start")

			counter := 1

			for {
				c.EmitMessage([]byte("some-data"))
				time.Sleep(60 * time.Second * 3)
				counter++

				if counter == 3 {
					break
				}
			}

			fmt.Println("End")

		})

		c.OnDisconnect(func() {
			fmt.Printf("\nConnection with ID: %s has been disconnected!\n", c.ID())
		})
	}) //end ws.OnConnection

}
```

Client javascript code:

```
$(function() {

	function connectToService() {
		if (window.conn) {
			return; //already connected
		}

		if (window.WebSocket) {
			conn = new WebSocket("ws://" + window.location.hostname + ":" + window.location.port + "/ws");

			window.conn.onopen = function(evt) {
				conn.send("Start");
				console.log("WS start", evt);
			};

			window.conn.onmessage = function(evt) {
				console.log("WS message", evt.data);
			};

			window.conn.onclose = function(evt) {
				conn = null;
				console.log("WS close", evt);
			};

		} else {
			window.conn = null;
			alert("No websocket support!");
		}
	}

	connectToService();

});
```

**Comment by kataras** [comment]
@nkev 
> ΚΑΛΗΝΥΧΤΑ! (I am from Izmir, Turkey :)) 

I just saw it __geitonastatourkika!

@sebtzm 

>  I have the same bug on Windows with Chrome.

I tried with chrome and it runs perfect, can you please try doing the same thing with `On(msg,callback)` and `Emit(evt,msg)` and tell me the results? We have serious bug if that doesnt work on some of you

**Comment by kataras** [comment]
@nkev 
> ΚΑΛΗΝΥΧΤΑ! (I am from Izmir, Turkey :)) 

I just saw it komşu!

@sebtzm 

>  I have the same bug on Windows with Chrome.

I tried with chrome and it runs perfect, can you please try doing the same thing with `On(msg,callback)` and `Emit(evt,msg)` and tell me the results? We have serious bug if that doesnt work on some of you

**Comment by sebtzm** [comment]
In my code, the error occurs only when the connection remains hanging for a long time 
(See line `time.sleep (60 * time.Second * 3)`).
If I call `c.EmitMessage` without waiting, the problem does not occur.
I tried to increase `WriteTimeout` and `PongTimeout` without any improvement.

To use `On (msg, callback)`and `Emit (evt, msg)` should I use iris-ws.js? 
I will try as soon as I can.

**Comment by kataras** [comment]
@sebtzm  
> To use On (msg, callback)and Emit (evt, msg) should I use iris-ws.js? 

You just need to add ```html <script src="/iris-ws.js"></script>``` on your page.html nothing more, try it and tell me the results please.

> I tried to increase WriteTimeout and PongTimeout without any improvement.
The ``` WriteTimeout ``` is your problem as I understand, which should be increased via ``` iris.Config.Websocket.WriteTimeout = ``` before ` iris.Websocket.OnConnection`

Also Upgrade Iris to its last version:  remove $GOPATH/src/github.com/kataras/iris and ``` go get -u github.com/kataras/iris ``` 

Read also the [HISTORY](https://github.com/kataras/iris/tree/master/HISTORY.md), thanks you!!

**Comment by kataras** [comment]
@sebtzm  
> To use On (msg, callback)and Emit (evt, msg) should I use iris-ws.js? 

You just need to add ```html <script src="/iris-ws.js"></script>``` on your page.html nothing more, try it and tell me the results please.

> I tried to increase WriteTimeout and PongTimeout without any improvement.

The ``` WriteTimeout ``` is your problem as I understand, which should be increased via ``` iris.Config.Websocket.WriteTimeout = ``` before ` iris.Websocket.OnConnection`

Also Upgrade Iris to its last version:  remove $GOPATH/src/github.com/kataras/iris and ``` go get -u github.com/kataras/iris ``` 

Read also the [HISTORY](https://github.com/kataras/iris/tree/master/HISTORY.md), thanks you!!

**Comment by sebtzm** [comment]
I tried with the last **rc-1** and `iris-ws.js`, but got the same error:

```
Server is listening at: 8080
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 3.0.0-rc.1

Wed, 15 Jun 2016 09:24:16 GMT: Running at 127.0.0.1:8080

On connection 'tAXZuVkXtwBXWUktVOuOGGfgZddKUDHocDzHudveAXNiChYfdfmdqVKklTbFLlOp'
On start
On end

Connection with ID: tAXZuVkXtwBXWUktVOuOGGfgZddKUDHocDzHudveAXNiChYfdfmdqVKklTbFLlOp has been disconnected!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x2c pc=0x60a9e9]

goroutine 14 [running]:
panic(0x9306a0, 0x12d14030)
        E:/DEVS/Go/src/runtime/panic.go:464 +0x326
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0x12e9f050, 0xcef2fc16, 0xe, 0xebde1ac, 0xcac800, 0x0, 0x0)
        <autogenerated>:35 +0x69
github.com/iris-contrib/websocket.(*Conn).write(0x12daa820, 0x8, 0xcef2fc16, 0xe, 0xebde1ac, 0xcac800, 0x12d1de2c, 0x2, 0x2, 0x0, ...)
        E:/PROJECTS/GO/src/github.com/iris-contrib/websocket/conn.go:293 +0xf0
github.com/iris-contrib/websocket.(*Conn).flushFrame(0x12daa820, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        E:/PROJECTS/GO/src/github.com/iris-contrib/websocket/conn.go:455 +0x653
github.com/iris-contrib/websocket.(*Conn).WriteMessage(0x12daa820, 0x8, 0xcbe2ec, 0x0, 0x0, 0x0, 0x0)
        E:/PROJECTS/GO/src/github.com/iris-contrib/websocket/conn.go:595 +0x112
github.com/kataras/iris/websocket.(*connection).write(0x12e9c0a0, 0x8, 0xcbe2ec, 0x0, 0x0, 0x0, 0x0)
        E:/PROJECTS/GO/src/github.com/kataras/iris/websocket/connection.go:84 +0x1de
github.com/kataras/iris/websocket.(*connection).writer(0x12e9c0a0)
        E:/PROJECTS/GO/src/github.com/kataras/iris/websocket/connection.go:98 +0x15a
created by github.com/kataras/iris/websocket.(*server).handleConnection
        E:/PROJECTS/GO/src/github.com/kataras/iris/websocket/server.go:92 +0x71
exit status 2
```

This is the code:

```
func setupWebSocket() {

	iris.Config.Websocket.Endpoint = "/ws" 
	// iris.Config.Websocket.PongTimeout = (30 * time.Minute)  //<- I also tried this
	// iris.Config.Websocket.WriteTimeout = (30 * time.Minute) //<- I also tried this

	ws := iris.Websocket //get the websocket server

	var myChatRoom = "room1"
	ws.OnConnection(func(c websocket.Connection) {

		fmt.Printf("On connection '%s' \n", c.ID())

		c.Join(myChatRoom)
		c.On("chat", func(message string) {

			fmt.Println("On start")

			counter := 1

			for {
				c.To(myChatRoom).Emit("chat", "From: "+c.ID()+": "+message)
				time.Sleep(60 * time.Second * 3)
				counter++

				if counter == 3 {
					break
				}
			}

			fmt.Println("On end")
		})

		c.OnDisconnect(func() {
			fmt.Printf("\nConnection with ID: %s has been disconnected!\n", c.ID())
		})
	}) //end ws.OnConnection

} //end setupWebSocket
```

Client code:

```
<script>
	$(function () {

		ws = new Ws("ws://" + window.location.hostname + ":" + window.location.port + "/ws");
		ws.OnConnect(function () {
			console.log("Websocket connection enstablished");
		});

		ws.OnDisconnect(function () {
			console.log("Ws disconnect")
		});

		ws.On("chat", function (message) {
			console.log(message)
		})

		$("#sendBtn").click(function () {
			ws.Emit("chat", "demo1");
		})

	})
</script>
```

Tests performed on Windows 10 with Chrome v. 51

**Comment by kataras** [comment]
@sebtzm  Upgrade and try again now please

**Comment by kataras** [comment]
@nkev  your issue should be fixed too now, please try again

**Comment by kataras** [comment]
@sebtzm  & @nkev Upgrade Iris  `go get -u github.com/kataras/iris`and try again now please

**Comment by kataras** [comment]
@sebtzm  & @nkev Upgrade Iris  `go get -u github.com/kataras/iris`and try again, please, should be fixed, thanks you!

**Comment by nkev** [comment]
I updated both iris and iris-contrib packages, but unfortunately in the iris-contrib/examples/websocket example, when I close the Safari browser I still get a panic:

```bash
Nuris-MBP:websocket nuri$ go run main.go
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 3.0.0-rc.1

Thu, 16 Jun 2016 19:18:22 GMT: Running at 127.0.0.1:8080

websocket: close 1006 (abnormal closure): unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x21bcd5]

goroutine 53 [running]:
panic(0x68eae0, 0xc82000a0d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0xc82029e6e0, 0xecef46621, 0xc8224cbe99, 0xaf6ea0, 0x0, 0x0)
	<autogenerated>:35 +0x75
github.com/iris-contrib/websocket.(*Conn).write(0xc8203b4240, 0x8, 0xecef46621, 0x224cbe99, 0xaf6ea0, 0xc820387cc0, 0x2, 0x2, 0x0, 0x0)
	/Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:293 +0x12c
github.com/iris-contrib/websocket.(*Conn).flushFrame(0xc8203b4240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:455 +0x713
github.com/iris-contrib/websocket.(*Conn).WriteMessage(0xc8203b4240, 0x8, 0xb147a0, 0x0, 0x0, 0x0, 0x0)
	/Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:595 +0x18c
github.com/kataras/iris/websocket.(*connection).write(0xc8203be090, 0x8, 0xb147a0, 0x0, 0x0, 0x0, 0x0)
	/Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/connection.go:83 +0x1b5
github.com/kataras/iris/websocket.(*connection).writer(0xc8203be090)
	/Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/connection.go:97 +0x1c3
created by github.com/kataras/iris/websocket.(*server).handleConnection
	/Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/server.go:92 +0x88
exit status 2
```

**Comment by nkev** [comment]
I would really like to see someone else who has a Macbook Pro to confirm the bug, just to eliminate the possibility of something else abnormal on my Macbook Pro.

**Comment by kataras** [comment]
Hmmm did you try 
```go
iris.Config.Websocket.WriteTimeout = time.Duration(30) * time.Minute // for example

```
?

**Comment by nkev** [comment]
I still get the error, unfortunately. I added your WriteTimeout line just before the connection line:
```go
iris.Websocket.OnConnection(func(c websocket.Connection) {
```

**Comment by kataras** [comment]
You upgraded also? then there is a serious problem and I need something to do my tests, I can't ask for you everytime to do that..I will find something

**Comment by nkev** [comment]
Yes, I upgraded both iris and iris-contrib. I think the first logical step is to find someone who develops with Iris on a Mac and have them try the websocket demo on Safari and Chrome together.

**Comment by kataras** [comment]
I will do one last think of mine now and I will ask you to test it again in 5 minutes if you could it will be nice, I did ask it from gitter one guy will do that but in later time, we need to fix it now for you :)

**Comment by kataras** [comment]
ok, @nkev  can you upgrade and test again? give me the stacktrace also

**Comment by nkev** [comment]
I'm driving to the office now to a meeting, but I will test a bit later and report back.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Jun 17, 2016 at 8:45 AM +1000, "Gerasimos Maropoulos" <notifications@github.com<mailto:notifications@github.com>> wrote:


ok, @nkev<https://github.com/nkev> can you upgrade and test again? give me the stacktrace also

-

**Comment by nkev** [comment]
No joy:

```bash
Nuris-MBP:websocket nuri$ go build main.go
Nuris-MBP:websocket nuri$ ./main
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 3.0.0-rc.1

Fri, 17 Jun 2016 12:28:32 GMT: Running at 127.0.0.1:8080


Connection with ID: IIAkbopaSgeYUjRZAyArEfbpBnhAKVjCDXpFXKNISlYFBlWeUEpHtOjmvuZZyXYK has been disconnected!websocket: close 1006 (abnormal closure): unexpected EOF

Connection with ID: xVamddDxlPveoKEStuKQBhwpOirLYGuUZFbtPKAbkFGAjVIFIRgHmaMMgylzZnkG has been disconnected!panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x21bf55]

goroutine 42 [running]:
panic(0x68ed00, 0xc82000a0e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0xc8203798a0, 0xecef55e7b, 0xc807d59534, 0xaf6ea0, 0x0, 0x0)
	<autogenerated>:35 +0x75
github.com/iris-contrib/websocket.(*Conn).write(0xc8203758c0, 0x8, 0xecef55e7b, 0x7d59534, 0xaf6ea0, 0xc8203aec00, 0x2, 0x2, 0x0, 0x0)
	/Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:294 +0x13a
github.com/iris-contrib/websocket.(*Conn).flushFrame(0xc8203758c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:458 +0x713
github.com/iris-contrib/websocket.(*Conn).WriteMessage(0xc8203758c0, 0x8, 0xb147a0, 0x0, 0x0, 0x0, 0x0)
	/Users/nuri/Dropbox/go/src/github.com/iris-contrib/websocket/conn.go:598 +0x18c
github.com/kataras/iris/websocket.(*connection).write(0xc8201f8e10, 0x8, 0xb147a0, 0x0, 0x0, 0x0, 0x0)
	/Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/connection.go:83 +0x1b5
github.com/kataras/iris/websocket.(*connection).writer(0xc8201f8e10)
	/Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/connection.go:97 +0x1c6
created by github.com/kataras/iris/websocket.(*server).handleConnection
	/Users/nuri/Dropbox/go/src/github.com/kataras/iris/websocket/server.go:92 +0x88
```

**Comment by sebtzm** [comment]
I tried with the last update, without success.

```
Server is listening at: 8080
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 3.0.0-rc.1

Fri, 17 Jun 2016 08:39:35 GMT: Running at 127.0.0.1:8080

On connection 'lFNjEjVKkeplvDphIBVoGcxNIHYyGhDArhttuCyBVFozEHXpJiyfdNMCcUsNJLtC'
On start
On end

Connection with ID: lFNjEjVKkeplvDphIBVoGcxNIHYyGhDArhttuCyBVFozEHXpJiyfdNMCcUsNJLtC has been disconnected!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x2c pc=0x60c729]

goroutine 41 [running]:
panic(0x9325a0, 0x12e14030)
        E:/DEVS/Go/src/runtime/panic.go:464 +0x326
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0x1307c2b0, 0xcef593bb, 0xe, 0x386c70f4, 0xcaf820, 0x0, 0x0)
        <autogenerated>:35 +0x69
github.com/iris-contrib/websocket.(*Conn).write(0x12f70280, 0x8, 0xcef593bb, 0xe, 0x386c70f4, 0xcaf820, 0x130cfdac, 0x2, 0x2, 0x0, ...)
        E:/PROJECTS/GO/src/github.com/iris-contrib/websocket/conn.go:294 +0xfc
github.com/iris-contrib/websocket.(*Conn).flushFrame(0x12f70280, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        E:/PROJECTS/GO/src/github.com/iris-contrib/websocket/conn.go:458 +0x653
github.com/iris-contrib/websocket.(*Conn).WriteMessage(0x12f70280, 0x8, 0xcc130c, 0x0, 0x0, 0x0, 0x0)
        E:/PROJECTS/GO/src/github.com/iris-contrib/websocket/conn.go:598 +0x112
github.com/kataras/iris/websocket.(*connection).write(0x12ff1860, 0x8, 0xcc130c, 0x0, 0x0, 0x0, 0x0)
        E:/PROJECTS/GO/src/github.com/kataras/iris/websocket/connection.go:83 +0x1e3
github.com/kataras/iris/websocket.(*connection).writer(0x12ff1860)
        E:/PROJECTS/GO/src/github.com/kataras/iris/websocket/connection.go:97 +0x18c
created by github.com/kataras/iris/websocket.(*server).handleConnection
        E:/PROJECTS/GO/src/github.com/kataras/iris/websocket/server.go:92 +0x71
exit status 2
```

**Comment by kataras** [comment]
This happens when you close the safari browser on OSX ?

**Comment by sebtzm** [comment]
I tried it on Windows with Chome.
Yesterday I tried with Firefox and Edge, I got the same error.

These are the steps:

1) I Launch the server.
2) I open the browser, and I click on #sendBtn (see above client code)
3) I receive the first message on console, I wait
4) I receive the second message on console, I wait.
5) After the exit of for-loop, program print "On end" (see above server code)
6) Program crashes with panic.

**Comment by kataras** [comment]
@nkev @sebtzm   The issue should be fixed now!! upgrade with ' go get -u github.com/kataras/iris`.

**Comment by kataras** [comment]
@nkev @sebtzm   The issue should be fixed now!! upgrade with `  go get -u github.com/kataras/iris` and verify me that is working, I borrowed a macos today

**Comment by nkev** [comment]
I can confirm it's fixed on Safari on Mac! Well done @Kataras!

**Comment by kataras** [comment]
@nkev  Thanks you, I added ` OnError(func(string))` also, to catch any internals errors comming from a connection

```go
iris.Websocket.OnConnection(func(c websocket.Connection){
   c.OnError(func(s string){
             
   })
})

```

So can we close this issue for good now ? !

**Comment by nkev** [comment]
Yes, of course!

**Comment by kataras** [comment]
Thanks for your issue report sir, any other suggestions are welcome

**Comment by sebtzm** [comment]
I confirm that it works on Windows too.
