### ISSUE TITLE
Party with API

### ISSUE THREAD

**Issue by cristian-sima** [kataras/iris#293]
Hi.

I was pretty enthusiastic of `iris.API` in the sense I can save a lot of time.

Therefore, lets say I have a dozens of companies, and for each company I want to have an `API` for `invoices`. So, my code is: 

```
func LoadAPI(api iris.MuxAPI) {
	cube := api.Party("/company/:company", middleware.GeneralDatabase)
	{
		cube.API("invoices", invoiceAPI{})
	}
}
```

where `invoiceAPI` is a simple example as [here](https://kataras.gitbooks.io/iris/content/using-handlerapi.html). Good, it works. But it has a problem:

For this url `company/16/invoices/7` the method `GetBy` it returns `16` rather than `7`. 

I read that it returns the first param. Good. But I thought the first param after the `API` starts, not the first of party.

I have tried this:

```
// users/:param1/:param2
func (u UserAPI) GetBy(id string, otherParameter string) {

}

```

but it tells me this: 

![image](https://cloud.githubusercontent.com/assets/12199042/16902516/93a93748-4c69-11e6-887f-7352126d255c.png)

I can see that at `PostBy` the systax is `/invoices/:param1` which is correct.

 For `GetBy` is just `/:param1` and not `/invoices/:param1`

Any idea? Am I wrong somewhere?

**Comment by cristian-sima** [comment]
That's really strange

If I do `log.Println("u.Params", u.Params)` I get 

`u.Params companyinvoices=16,param1=in`

**Comment by kataras** [comment]
@cristian-sima Yes this happens because `Params` on Iris has a String method also to help you view your parameters with a simple println :)

**Comment by cristian-sima** [comment]
@kataras Thanks. Looking forward for it

**Comment by kataras** [comment]
This should fix the issue, can you verify please?

**Comment by cristian-sima** [comment]
It is not fixed.

Let's take for example this full implementation:

```go
package main

import "github.com/kataras/iris"

// --- middlewares

func _1stMiddlware(context *iris.Context) {

	context.Write("Params are: ", context.Params)
	context.Write("\n\n")
	context.Write("The id of company is: ", context.Param("company"))
	context.Write("\n\n")
	context.Write("1. This is the first middleware \n")

	context.Next()
}

func _2ndMiddleware(context *iris.Context) {
	context.Write("2. This is the second middleware \n")
	context.Next()
}

func _3rdMiddleware(context *iris.Context) {
	context.Write("3. This is the 3rd middleware \n")
	context.Next()
}

func _4thMiddlware(context *iris.Context) {
	context.Write("4. This is the 4th middleware \n")
	context.Next()
}

var firstTwoMiddlewares = []iris.HandlerFunc{
	_1stMiddlware,
	_2ndMiddleware,
}

var lastTwoMiddlewares = []iris.HandlerFunc{
	_3rdMiddleware,
	_4thMiddlware,
}

// --- invoiceAPI

type invoiceAPI struct {
	*iris.Context
}

// GET /invoices
func (api invoiceAPI) Get() {
	api.Write("List all the invoices \n")
}

// GET /:param1 which its value passed to the id argument
func (api invoiceAPI) GetBy(id string) {
	api.Write("Get the invoice with id: %s", id, "\n")
}

// PUT /invoices
func (api invoiceAPI) Put() {
	api.Write("PUT invoice \n")
}

// POST /invoices/:param1
func (api invoiceAPI) PostBy(id string) {
	api.Write("POST invoice \n")
}

// DELETE /invoices/:param1
func (api invoiceAPI) DeleteBy(id string) {
	api.Write("Get the invoice with id: %s", id, "\n")
}

// --- main

func main() {

	api := iris.Party("/api")

	cube := api.Party("/company/:company", firstTwoMiddlewares...)
	{
		cube.API("invoices", invoiceAPI{})
	}
	cube.UseFunc(lastTwoMiddlewares...)

	iris.Listen("127.0.0.1:8000")
}
```

The examples which work should be:

1. `http://127.0.0.1:8000/api/company/16/invoices` -> this one should show all the invoices, but it shows:

```
Params are: %!(EXTRA iris.PathParameters=companyinvoices=16,param1=invoices)

The id of company is: %!(EXTRA string=)

1. This is the first middleware 
2. This is the second middleware 
Get the invoice with id: invoices%!(EXTRA string=
)
```

So, it seems that `/api/company/16/invoices` behaves as `api/company/16/invoices/:invoiceID` and it returns the string `invoices` as the invoice `ID`.


2.  `http://127.0.0.1:8000/api/company/16/invoices/1` -> this one should show the info about the invoice with the ID `1`, but it shows:

```
Not Found
```

---

Another problem is the parameters:

```
Params are: %!(EXTRA iris.PathParameters=companyinvoices=16,param1=invoices)
```

Therefore, the commit does not solve the problems

**Comment by kataras** [comment]
@cristian-sima 

The commit fixed the issue but you did a small 'mistake' here:

` cube.API("invoices", invoiceAPI{})` instead of ` cube.API("/invoices", invoiceAPI{})` 

> the route's paths always starts with "/", when the client navigates, the router works without "" also ,
but the developer should always prepend the slash ("/") to register the routes

Working example:

```go
package main

import "github.com/kataras/iris"

// --- middlewares

func _1stMiddlware(context *iris.Context) {

	context.Write("Params are: %s", context.Params.String())
	context.Write("\n\n")
	context.Write("The id of company is: %s", context.Param("company"))
	context.Write("\n\n")
	context.Write("1. This is the first middleware \n")

	context.Next()
}

func _2ndMiddleware(context *iris.Context) {
	context.Write("2. This is the second middleware \n")
	context.Next()
}

func _3rdMiddleware(context *iris.Context) {
	context.Write("3. This is the 3rd middleware \n")
	context.Next()
}

func _4thMiddlware(context *iris.Context) {
	context.Write("4. This is the 4th middleware \n")
	context.Next()
}

var firstTwoMiddlewares = []iris.HandlerFunc{
	_1stMiddlware,
	_2ndMiddleware,
}

var lastTwoMiddlewares = []iris.HandlerFunc{
	_3rdMiddleware,
	_4thMiddlware,
}

// --- invoiceAPI

type invoiceAPI struct {
	*iris.Context
}

// GET /invoices
func (api invoiceAPI) Get() {
	api.Write("List all the invoices \n")
}

// GET /:param1 which its value passed to the id argument
func (api invoiceAPI) GetBy(id string) {
	api.Write("Get the invoice with id: %s", id, "\n")
}

// PUT /invoices
func (api invoiceAPI) Put() {
	api.Write("PUT invoice \n")
}

// POST /invoices/:param1
func (api invoiceAPI) PostBy(id string) {
	api.Write("POST invoice \n")
}

// DELETE /invoices/:param1
func (api invoiceAPI) DeleteBy(id string) {
	api.Write("Get the invoice with id: %s \n", id)
}

// --- main

func main() {

	api := iris.Party("/api")

	cube := api.Party("/company/:company", firstTwoMiddlewares...)
	{
		cube.API("/invoices", invoiceAPI{})
	}
	cube.DoneFunc(lastTwoMiddlewares...)

	iris.Listen("127.0.0.1:8000")
}
```

I made the `API` to auto- prepend the "/" if the developer didn't added it, but I advise you to always prepend the  slash "/" *

**Comment by kataras** [comment]
@cristian-sima 

The commit fixed the issue but you did a small 'mistake' here:

` cube.API("invoices", invoiceAPI{})` instead of ` cube.API("/invoices", invoiceAPI{})` 

> the route's paths always starts with "/", when the client navigates, the router works without slash also ,
but the developer should always prepend the slash ("/") to register the routes

Working example:

```go
package main

import "github.com/kataras/iris"

// --- middlewares

func _1stMiddlware(context *iris.Context) {

	context.Write("Params are: %s", context.Params.String())
	context.Write("\n\n")
	context.Write("The id of company is: %s", context.Param("company"))
	context.Write("\n\n")
	context.Write("1. This is the first middleware \n")

	context.Next()
}

func _2ndMiddleware(context *iris.Context) {
	context.Write("2. This is the second middleware \n")
	context.Next()
}

func _3rdMiddleware(context *iris.Context) {
	context.Write("3. This is the 3rd middleware \n")
	context.Next()
}

func _4thMiddlware(context *iris.Context) {
	context.Write("4. This is the 4th middleware \n")
	context.Next()
}

var firstTwoMiddlewares = []iris.HandlerFunc{
	_1stMiddlware,
	_2ndMiddleware,
}

var lastTwoMiddlewares = []iris.HandlerFunc{
	_3rdMiddleware,
	_4thMiddlware,
}

// --- invoiceAPI

type invoiceAPI struct {
	*iris.Context
}

// GET /invoices
func (api invoiceAPI) Get() {
	api.Write("List all the invoices \n")
}

// GET /:param1 which its value passed to the id argument
func (api invoiceAPI) GetBy(id string) {
	api.Write("Get the invoice with id: %s", id, "\n")
}

// PUT /invoices
func (api invoiceAPI) Put() {
	api.Write("PUT invoice \n")
}

// POST /invoices/:param1
func (api invoiceAPI) PostBy(id string) {
	api.Write("POST invoice \n")
}

// DELETE /invoices/:param1
func (api invoiceAPI) DeleteBy(id string) {
	api.Write("Get the invoice with id: %s \n", id)
}

// --- main

func main() {

	api := iris.Party("/api")

	cube := api.Party("/company/:company", firstTwoMiddlewares...)
	{
		cube.API("/invoices", invoiceAPI{})
	}
	cube.DoneFunc(lastTwoMiddlewares...)

	iris.Listen("127.0.0.1:8000")
}
```

I made the `API` to auto- prepend the "/" if the developer didn't added it, but I advise you to always prepend the  slash "/" *

**Comment by cristian-sima** [comment]
Yep. I confirm also for this that it is working.

Thank you for your time :)

**Comment by kataras** [comment]
I thanks you for contributing to this framework, again hope you the bests, now you should be dedicated more than ever!!
