### ISSUE TITLE
StaticWeb not functioning properly

### ISSUE THREAD

**Issue by allen13** [kataras/iris#350]
Current setup using iris master:

http.StaticWeb("/static", "./static", 1)

Steps to reproduce:

http://localhost:5608/static/

Expected:

GET http://localhost:5608/static/index.html 

Actual:

GET http://localhost:5608/index.html - cannot open dir index "./static": cannot access directory without index page. Directory "./static"

Basically StaticWeb redirects all requests to root.

Fix:

I was able to fix this issue with https://github.com/kataras/iris/pull/335 however this was declined. I may be doing something wrong on my side, but the code is still behaving in an unexpected way.

**Comment by kataras** [comment]
Could you tell me what fasthttp do you have? (SetRequestURI is fasthttp's function), because on my machine is working

**Comment by kataras** [comment]
Could you tell me what fasthttp do you have? (SetRequestURI is fasthttp's function), because on my machine is working just fine, as I answered you on the PR

**Comment by kataras** [comment]
Could you tell me what fasthttp do you have? (SetRequestURI is fasthttp's function), because on my machine is working just fine, as I answered you on the PR.  I cannot directly accept your PR because you didn't read the CONTRIBUTION file, but I would like to help me in order to fix this issue you have on StaticWeb.

**Comment by allen13** [comment]
I'm currently on master
{
	"ImportPath": "github.com/valyala/fasthttp",
	"Comment": "v20160617-26-g45697fe",
	"Rev": "45697fe30a130ec6a54426a069c82f3abe76b63d"
}

**Comment by kataras** [comment]
Operating system?

**Comment by allen13** [comment]
Environment
Operating system: OSX 10.11.6
Golang: go1.6.2 darwin/amd64
Project line reference: https://github.com/allen13/golerta/blob/master/app/app.go#L49

**Comment by kataras** [comment]
Ok, can you try this instead of your `http.StaticWeb` please ( I want to see why on windows is working and not on osx)?
```go
http.Get("/static", http.StaticHandler("./static", 1, false, true, []{"index.html})
```

and tell me the results please?

**Comment by allen13** [comment]
Using the code @kataras provided:

It serves the index.html properly when accessing /static/ but it breaks the path for the other assets in the static folder. For example, /static/js/app.js becomes /js/app.js when served from this location. 

If I call the full path to the index /static/index.html everything works properly

**Comment by kataras** [comment]
Yes I just tested that, same here, please wait some minutes I will come back soon

**Comment by kataras** [comment]
Fixed, the issue was the `StripPrefix` , I added an example for that reason here: https://github.com/iris-contrib/examples/tree/master/static_web , thanks for reporting!!

**Comment by kataras** [comment]
Fixed, the issue was the `StripPrefix` , I added an example for that reason here: https://github.com/iris-contrib/examples/tree/master/static_web , thanks for reporting!!

Please verify that it works on you too

**Comment by allen13** [comment]
This still isn't functioning fully. Setting the strip down to 0 causes issues with the sub resources. It works in your example because your serving from root and it doesn't add anything to the directory path.

Here is the result:
GET http://localhost:5608/static/css/app.css - cannot open file "./static/static/css/app.css": open ./static/static/css/app.css: no such file or directory

**Comment by kataras** [comment]
Did you see the example? if `/static` then use `1` if `/` then use `0` , please download the example, test it, tell me if that worked for you, if yes, then try it to your app and tell me the results, I 'm waiting, thanks you!!

**Comment by allen13** [comment]
Just tried example. It works perfectly. Going to try a few experiments.

**Comment by allen13** [comment]
So currently StaticWeb only seems to work reliably from the root path, I can't use a prefix like /static. I'm going to rearrange my routes so that static is now used from root. It looks better like this anyways. While I would still consider this an issue, I'm going to consider this fixed as I can work around it. Thanks for your help!

**Comment by kataras** [comment]
Why not working on `/static` , did the example didn't worked for you?(it has commented code that was tested also, use that), if anyone else has the same issue like you with the current StaticWeb then I will make a pr to fasthttp , or you can already make a patch for fasthttp's static handler
