### ISSUE TITLE
Gzip Middleware broken

### ISSUE THREAD

**Issue by kryptodev** [kataras/iris#42]
`"github.com/kataras/iris/middleware/gzip"`
`iris.Use(gzip.Gzip(gzip.DefaultCompression))`
To put simply, when the iris supplied gzip middleware is on, when you refresh the page 2~4 times, the next times you try to open the page, it would be blank with 200 status code.

I experimented with and without gzip middleware and it seems to only happen when gzip middleware is active.

Thank you :)

**Comment by kataras** [comment]
@kryptodev Hmmm I didn't notice it, I will look into this, tommorow, I'm already 30h+ asleep and my eyes are closing, I will notify you when I fix this, again thanks!!

**Comment by kryptodev** [comment]
I checked, it tends to affect all routes.  Either the page comes up blank or it's loading forever.
Without gzip everything is smooth.

**Comment by kataras** [comment]
@kryptodev  Yes I made recent change ( before some hours) I fix the issue ( no the middleware but the generic blank page) check again please

**Comment by kataras** [comment]
@kryptodev  Just fixed the issue with the middleware ( at least on my example is working fine now) can you test again and close the issue if that's really fixed?

**Comment by kryptodev** [comment]
```
c.WriteText(200, `User-agent: *
Disallow:`)
```
Routes that have that seem to not work with gzip enabled(works otherwise).

***
Unrelated to this issue but WriteXML does not output XML like this site for examlple: https://xmlsitemapgenerator.org/sitemap.xml

Instead it causes the browser to download the file. 

:) Hope you are taking rest.

**Comment by kataras** [comment]
@kryptodev Yes? I though the tests are working sht... I will fix it this is the easier part, I have problem because the gzip on my configuration is working I can't understand what's wrong can you give me a snippet of your code ?

**Comment by kryptodev** [comment]
I'll explain,  I have this route configured:
`iris.Get("/test", test)`

And this is the handler function:
```
func test(c *iris.Context) {
	c.WriteText(200, `Random Text`)
}
```

So when gzip is enabled, that route doesn't work. Just keeps loading. Without gzip it's fine.
Tested with the latest revision of Iris.

**Comment by kataras** [comment]
Okay I'm making a 5th router to solve one previous problem, when I finish it I will look it into this I think I know what's the problem, thanks you I will notify you

**Comment by xpbliss** [comment]
Too short strings to gzip?

**Comment by kataras** [comment]
@kryptodev after so much time I released that the problem was inside the io.WriteString, I had to check the 500 lines of their code to understand it.. lol anyway the only thing we can make for it is: 1. replace the io.WriteString to -> .Write([]byte("thestring")) or make new functions especialy for 'pure' write? what do you thing ?

**Comment by kataras** [comment]
@kryptodev  Ok I think it's ok now, can you check if that is fixed? and the xml should be ok now*

**Comment by kryptodev** [comment]
Yes it's fixed but WriteXML is still not working as intended. Returns empty page without gzip enabled.

With Gzip enabled it causes browser to download an empty sitemap.xml file.


```Go
func routeSEOSitemap(c *iris.Context) {
	c.WriteXML(200, []byte(
	`<?xml version="1.0" encoding="UTF-8"?>` +
	`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">` +
	`<url><loc>https://site.com/home</loc></url>` +
	`<url><loc>https://site.com/news</loc></url>` +
	`<url><loc>https://site.com/community/</loc></url>` +
	`<url><loc>https://site.com/login</loc></url>` +
	`<url><loc>https://site.com/register</loc></url>` +
	`<url><loc>https://site.com/store</loc></url>` +
	`<url><loc>https://site.com/chat</loc></url>` +
	`<url><loc>https://site.com</loc></url>` +
	`</urlset>`))
}
```

**Comment by kataras** [comment]
@kryptodev  I covert the WriteXML to RenderXML and put the WriteXML in the use you want ( which is the correct usecase) , you can also call just .XML(`your xml contnets here`) //default http status 200  verify it please and if fixed close the issue

**Comment by kryptodev** [comment]
Fixed :)
